### ISSUE TITLE
Job: cvmfs_mounts are saved as text

### ISSUE THREAD

**Issue by roksys** [reanahub/reana-db#33]
[cvmfs_mounts](https://github.com/reanahub/reana-db/blob/8574f8f89ffd65ef41db06424b9488fa5ab2128d/reana_db/models.py#L200) field of Job model is saved as a text. It should be Boolean.

**Comment by tiborsimko** [comment]
Actually it should well be the text in the models, since the value is not Boolean but a list of CVMFS volumes that the user wanted to mount for the workflow to run, such as "atlas.cern.ch,atlas-condb.cern.ch". See also https://reana.readthedocs.io/en/latest/userguide.html#declare-necessary-resources

(IIRC a special value "false" was used to indicate that no CVMFS volume should be mounted, because empty string as a default value was causing some troubles with False values in Bravado client scenarios)

**Comment by diegodelemos** [comment]
Exactly, it is [text right now](https://github.com/reanahub/reana-db/blob/master/reana_db/models.py#L212). This issue should go to RWC, where we [conciously set it to `'false'`](https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/workflow_run_manager.py#L155-L168) when there are no CVMFS recourse requests.

I guess that, to be congruet, we should just not set the variable when there are not CVMFS recources requested and change in the engines to fall back to an empty string [instead of `'false'`](https://github.com/reanahub/reana-workflow-engine-yadage/blob/c4c12b529401081e701b8060c2c02c9779863c6c/reana_workflow_engine_yadage/config.py#L32), and then [send it to RJC](https://github.com/reanahub/reana-workflow-engine-yadage/blob/c4c12b529401081e701b8060c2c02c9779863c6c/reana_workflow_engine_yadage/externalbackend.py#L126) only if it actually contains any CVMFS repo (the field is not required in the API) so we aboid problems with Bravado's empty strings/booleans etc... 

The motivation behing this is mainly because we end up inside RJC code having a CVMFS mount called `false` and it is confusing.

**Comment by diegodelemos** [comment]
Moved to RWC, https://github.com/reanahub/reana-workflow-controller/issues/206.
