### ISSUE TITLE
models: separate workflows and interactive sessions

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-db#89]
Currently, interactive sessions of a user are stored together in the workflows in the same table:

```
class Workflow(Base, Timestamp):
    ...
    interactive_session = Column(Text)
    interactive_session_name = Column(Text)
    interactive_session_type = Column(Text)
```

We need to separate them into a new table.

This would allow for (1) having more than one session on a workflow workspace; (2) opening interactive sessions without necessarily having any workflow yet.

The implementation can go by having a `InteractiveSession` table similar `Workflow` table, then link it to the user and optionally to a workflow, perhaps with a ternary `user_workflow_session` table.

Let's design a new data model holding such a structure.

Let's amend current logic that opens workflows to follow this new structure.

Let's write alembic upgrade recipe to make sure upgrades are smooth.

(And allowing the opening of more than one session e.g. regular Jupyter notebook, e.g. spark notebook, i.e. the same jupyter but with a different docker container, can be thought of later.)

**Comment by audrium** [comment]
There are still couple of problems which are not yet solved:
- Integrity error is raised on workflow deletion - we need to do cascade deletion for InteractiveSession and UserWorkflowSession rows on this case
- RWC tests are also complaining about the Integrity error since `sample_serial_workflow_in_db` fixture on test teardown is being deleted
- `test_start_interactive_workflow_k8s_failure` test in RWC is still failing for some strange reason
